# Tutorial

```kotlin
:help
```

## ktor-client

Use this library to make HTTP requests.

```kotlin
%use ktor-client

http.get("https://jsonplaceholder.typicode.com/posts").bodyAsText()
```

## kandy

It is a plotting library.

```kotlin
%use kandy

posts.plot {
    x { it.userId }
    y { it.title.split("\\s+".toRegex()).size }
    geomBar(stat = "identity")
    theme {
        axis.text.x.angle = 45
        axis.text.x.hjust = 1
    }
}
```

In [1]:
%use ktor-client
%use kandy
%use dataframe

org.jetbrains.kotlinx.n(ReplLibraryException.kt:40)
	... 45 more
Caused by: java.lang.RuntimeException: ERROR Failed to resolve [Dependency(value=org.jetbrains.kotlinx:dataframe-jupyter:1.0.0-Beta4n, hasSources=MAYBE, isMultiplatform=NO)]:
File 'org.jetbrains.kotlinx:dataframe-jupyter:1.0.0-Beta4n' not found
The following artifacts could not be resolved: org.jetbrains.kotlinx:dataframe-jupyter:jar:1.0.0-Beta4n (absent): Could not transfer artifact org.jetbrains.kotlinx:dataframe-jupyter:jar:1.0.0-Beta4n from/to https___repo.maven.apache.org_maven2_ (https://repo.maven.apache.org/maven2/): GET request of: org/jetbrains/kotlinx/dataframe-jupyter/1.0.0-Beta4n/dataframe-jupyter-1.0.0-Beta4n.jar from https___repo.maven.apache.org_maven2_ failed
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.configureDependencies$lambda$2(CellExecutorImpl.kt:234)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.ignoreDependencyErrorsIfNeeded(CellExecutorImpl.kt:246)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.configureDependencies(CellExecutorImpl.kt:229)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.doAddLibraries$lambda$0(CellExecutorImpl.kt:179)
	at org.jetbrains.kotlinx.jupyter.exceptions.ReplLibraryExceptionKt.rethrowAsLibraryException(ReplLibraryException.kt:40)
	... 62 more

org.jetbrains.kotlinx.jupyter.exceptions.ReplInterruptedException: The execution was interrupted

In [ ]:
val users = http.get("https://jsonplaceholder.typicode.com/users").deserializeJson()
users

In [6]:
val usersDF = users.toDataFrame()
usersDF

id,name,username,email,address,phone,website,company
1,Leanne Graham,Bret,Sincere@april.biz,"Address(street=Kulas Light, suite=Apt...",1-770-736-8031 x56442,hildegard.org,"Company(name=Romaguera-Crona, catchPh..."
2,Ervin Howell,Antonette,Shanna@melissa.tv,"Address(street=Victor Plains, suite=S...",010-692-6593 x09125,anastasia.net,"Company(name=Deckow-Crist, catchPhras..."
3,Clementine Bauch,Samantha,Nathan@yesenia.net,"Address(street=Douglas Extension, sui...",1-463-123-4447,ramiro.info,"Company(name=Romaguera-Jacobson, catc..."
4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"Address(street=Hoeger Mall, suite=Apt...",493-170-9623 x156,kale.biz,"Company(name=Robel-Corkery, catchPhra..."
5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"Address(street=Skiles Walks, suite=Su...",(254)954-1289,demarco.info,"Company(name=Keebler LLC, catchPhrase..."
6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"Address(street=Norberto Crossing, sui...",1-477-935-8478 x6430,ola.org,"Company(name=Considine-Lockman, catch..."
7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"Address(street=Rex Trail, suite=Suite...",210.067.6132,elvis.io,"Company(name=Johns Group, catchPhrase..."
8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"Address(street=Ellsworth Summit, suit...",586.493.6943 x140,jacynthe.com,"Company(name=Abernathy Group, catchPh..."
9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"Address(street=Dayna Park, suite=Suit...",(775)976-6794 x41206,conrad.com,"Company(name=Yost and Sons, catchPhra..."
10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"Address(street=Kattie Turnpike, suite...",024-648-3804,ambrose.net,"Company(name=Hoeger LLC, catchPhrase=..."

In [26]:
val emailTLD = usersDF
    .add("emailTLD") { it.email.substringAfterLast('.') }
    .groupBy("emailTLD").count()
emailTLD

emailTLD,count
biz,3
tv,1
net,1
org,1
ca,1
info,1
me,1
io,1

In [31]:
emailTLD.plot {
    layout.title = "User Email Top-level Domain Distribution"
    barsH {
        y(emailTLD) { axis.name = "TLD" }
        x(count) { axis.name = "count" }
        alpha = 0.75
        fillColor(emailTLD) {
            scale = categoricalColorHue()
        }
    }
}

In [ ]:
USE {
    dependencies("com.example:template-project-persistence:0.0.1-SNAPSHOT")
}

val url = "jdbc:postgresql://localhost:5432/example"
val username = "test"
val password = "12345"

val dbConfig = DbConnectionConfig(url, username, password)

val exampleDF = DataFrame.readSqlTable(dbConfig, "example").cast<com.example.templateproject.persistence.entity.Example>()
exampleDF

In [10]:
exampleDF
//    .filter { it.last_modified_date != null }
    .filter { it.name.contains('1') }
    .forEach { println(it) }

In [ ]:
%use spring
import com.example.templateproject.core.service.ExampleService

USE {
    dependencies("com.example:template-project-core:0.0.1-SNAPSHOT")
}

val ctx = applicationContext
val myService = ctx.getBean(ExampleService::class.java)
myService.deleteEntity(1L)